fail_fast: false
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks-docker
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.138.0
    hooks:
      - id: semgrep
        name: Semgrep SAST
        args:
          - --config=p/security-audit
          - --config=p/javascript
          - --config=p/nodejs
          - --config=p/owasp-top-ten
          - --error
          - --skip-unknown-extensions
        files: \.(js|ts)$
        exclude: node_modules/
  - repo: local
    hooks:
      - id: npm-audit
        name: NPM Audit - SCA
        entry: bash ./scripts/npm_audit_summary.sh
        language: system
        pass_filenames: false
        files: package(-lock)?\.json$
      - id: dast-zap-scan
        name: Run ZAP scan on application
        entry: bash ./scripts/DAST_zap.sh
        language: system
        pass_filenames: false
