name: 01-secret-scanning

on:
  pull_request:
  push:
    branches:
      - main

# Cancel previous runs if a new commit is pushed to the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret-scanning:
    name: Secret Scanning - ${{ matrix.tool }}
    runs-on: [arc-runner-set]
    timeout-minutes: 10
    permissions:
      contents: read           # Read repository code for scanning
      pull-requests: read      # Read PR metadata and comments
      security-events: write   # Upload SARIF to GitHub Advanced Security
    strategy:
      fail-fast: false
      matrix:
        tool: [trivy, gitleaks]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Trivy (JSON for Summary)
        if: matrix.tool == 'trivy'
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          hide-progress: true
          format: json
          output: trivy-results.json
          scanners: secret
          severity: HIGH,CRITICAL

      - name: Run Trivy (SARIF for Code Scanning)
        id: trivy-sarif
        if: matrix.tool == 'trivy'
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          hide-progress: true
          format: sarif
          output: trivy-results.sarif
          scanners: secret
          severity: HIGH,CRITICAL
          limit-severities-for-sarif: true
          exit-code: 1

      - name: Upload Trivy SARIF
        if: always() && matrix.tool == 'trivy' && hashFiles('trivy-results.sarif') != ''
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Generate Trivy Summary
        if: always() && matrix.tool == 'trivy'
        continue-on-error: true
        run: |
          if [[ -f trivy-results.json ]]; then
            echo "## 🔓 Trivy Secret Scanning Results" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY

            HAS_SECRETS=$(jq '[.Results[]? | select(.Secrets != null) | .Secrets[]] | length' trivy-results.json)

            if [[ "$HAS_SECRETS" -gt 0 ]]; then
              echo "| Target | Rule ID | Category | Severity | Start Line | End Line | Match |" >> $GITHUB_STEP_SUMMARY
              echo "|--------|---------|----------|----------|------------|----------|-------|" >> $GITHUB_STEP_SUMMARY

              jq -r '.Results[]? | select(.Secrets != null) | .Target as $target | .Secrets[] | "| \($target) | \(.RuleID) | \(.Category) | \(.Severity) | \(.StartLine // "N/A") | \(.EndLine // "N/A") | `REDACTED` |"' trivy-results.json >> $GITHUB_STEP_SUMMARY
            else
              echo "✅ No secrets detected!" >> $GITHUB_STEP_SUMMARY
            fi

            echo "" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Fail if Trivy found secrets
        if: matrix.tool == 'trivy' && steps.trivy-sarif.outcome == 'failure'
        run: exit 1

      - name: Run Gitleaks
        if: matrix.tool == 'gitleaks'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: Upload Gitleaks SARIF
        if: always() && matrix.tool == 'gitleaks'
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif